### ISSUE TITLE
Rework `POST /change-password` endpoint to make it simpler

### ISSUE THREAD

**Issue by Syndesi** [ember-nexus/api#280]
The `POST /change-password` endpoint is currently using the following request body scheme:

```json
{
  "type": "ActionChangePassword",
  "currentPassword": "1234",
  "newPassword": "9876",
  "data": {
    "<identifier>": "test@example.com"
  }
}
```

The user identifier at `data.<identifier>` is not really intuitive, especially because no other properties within `data` will be used anyways. Furthermore, as `<identifier>` depends on the instance's configuration, it is unknown without executing `GET /instance-configuration` as well, making the current implementation both unintuitive as well as hard to use.

The current solution was developed during #121 .

The proposed solution is as following:

```json
{
  "type": "ActionChangePassword",
  "currentPassword": "1234",
  "newPassword": "9876",
  "uniqueUserIdentifier": "test@example.com"
}
```

---

### Tasks

- [x] Change endpoint while keeping the old behavior available. Keep the old behavior behind a feature flag which is on by default, and will be disabled with the release of version `0.2.0`.
- [x] Change the variable name `user` to `uniqueUserIdentifier` in the `POST /token` endpoint, keep the old logic available behind a feature flag as well.
- [x] Change the endpoint `POST /register` in a similar fashion.
- [x] Update unit tests. Mark old tests as deprecated.
- [x] Update feature tests.
- [x] Update documentation, especially graph & example generation.
- [x] Mark this as a breaking change in the change log.
- [x] Add new task in CI/CD for old, replaced feature tests.
