### ISSUE TITLE
Change current license AGPL 3 to source first

### ISSUE THREAD

**Issue by Syndesi** [ember-nexus/api#345]
According to https://github.com/ember-nexus/governance/issues/3 the license of this repository will be changed from AGPL 3 to [source first](https://gitlab.futo.org/videostreaming/grayjay/-/blob/master/LICENSE.md).

While this is an important change, this does **not** affect functionality as defined in the [semantic versioning specification](https://semver.org/#spec-item-8):

> Major version X (X.y.z | X > 0) MUST be incremented if **any backward incompatible changes are introduced to the public API**. It MAY also include minor and patch level changes. Patch and minor versions MUST be reset to 0 when major version is incremented.

Therefore this change will be rolled out with the next release, regardless of its type (major / minor / patch).

### Tasks

- [x] Change the license in all files:
  - [x] Readme, including shields.
  - [x] Readme in documentation, including shields.
  - [x] Readme on Dockerhub, including shields.
  - [x] Dockerfile. Note that the source first license does not have a SPDX identifier yet, therefore it should be referenced as `LicenseRef-Source-First-License-1.1`.
  - [x] `composer.json`.
  - [x] `LICENSE`
- [x] Replace mentions of "open source" with "source first".
- [ ] Create and publish new release.
